"""new_audio_to_phoneme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5LYDxYGUriDJkB-5epFh9xNhsEGTFCG
"""

import torch
import torchvision
import torchaudio
import whisperx
import numpy as np
from phonemizer import phonemize
from phonemizer.backend.espeak.wrapper import EspeakWrapper

# Testing this fix for Windows
EspeakWrapper.set_library(r"C:\Program Files\eSpeak NG\libespeak-ng.dll")

print("torch:", torch.__version__)
print("torchvision:", torchvision.__version__)
print("torchaudio:", torchaudio.__version__)

WORK_DIR = "C:/Users/SPIRO/documents/auto-lip-sync/test_audios"

audio_name = "i-live-alone"

audio_file = f"{WORK_DIR}/{audio_name}.wav"
text = ""

print(audio_file)


use_cuda_if_avail = True
if use_cuda_if_avail and torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

# Have to do this for CPU
if not hasattr(np, "NaN"):
  np.NaN = np.nan

audio_file = audio_file
batch_size = 16 # reduce if low on GPU mem
compute_type = "float16" if device == "gpu" else "int8" # originally float16. change to "int8" if low on GPU mem (may reduce accuracy)

# 1. Transcribe with original whisper (batched)
model = whisperx.load_model("large-v2", device, compute_type=compute_type, language="en")

audio = whisperx.load_audio(audio_file)
result = model.transcribe(audio, batch_size=batch_size)
transcript = model.transcribe(audio, batch_size=batch_size)["segments"]
print(transcript) # before alignment

# Use phonemize to get the transcript in terms of phonemes
phone_transcript = [{"text": phonemize(segment["text"]), "start":segment["start"], "end":segment["end"]} for segment in transcript]

# 2. Align whisper output
aligner_model = "facebook/wav2vec2-large-960h-lv60"

model_a, metadata = whisperx.load_align_model(language_code=result["language"], device=device, model_name=aligner_model)

result = whisperx.align(phone_transcript, model_a, metadata, audio, device, return_char_alignments=True)

print(result["segments"]) # after alignment

words = result["segments"][0].get('words')
# for word in words:
#   print(word["word"], word["start"], word["end"])

# print(phone_transcript[0]['text'])
phonemes = phone_transcript[0]['text']

# for r in result["segments"][0].get('chars'):
#   print(r)

phoneme_timings = result["segments"][0].get('chars')[:-1]

# for phoneme in phoneme_timings:
#   print(phoneme)

# Microsoft mapping
ipa_to_viseme = {
  "sil":0,

  # Low/mid vowels
  "æ":1, "ə":1, "ʌ":1,
  "ɑ":2, "ɐ":2, "a":2,
  "ɔ":3, "ɒ":3,
  "ɛ":4, "e":4,
  "ɝ":5, "ɜ":5, "ɚ":5,

  # High front vowels
  "j":6, "i":6, "ɪ":6, "ᵻ":6,

  # High back vowels
  "w":7, "u":7, "ʊ":7,

  # Other vowels/diphthongs
  "o":8,
  "aʊ":9,
  "ɔɪ":10,
  "aɪ":11,

  # Consonants
  "h":12,
  "ɹ":13,
  "l":14,
  "s":15, "z":15,
  "ʃ":16, "tʃ":16, "dʒ":16, "ʒ":16,
  "ð":17,
  "f":18, "v":18,
  "d":19, "t":19, "n":19, "θ":19, "ɾ":19, "ʔ":19,
  "k":20, "ɡ":20, "ŋ":20,
  "p":21, "b":21, "m":21
}

def normalize_token(token: str) -> list[str]:
  if not token:
    return []

  token = token.strip()

  # Syllabic consonants → base consonant
  if token in ["n̩", "l̩", "m̩"]:
    return [token[0]]

  # Rare combined tokens
  if token == "əl":
    return ["ə", "l"]

  # Split vowel+r if combined
  if token.endswith("ɹ") and len(token) > 1:
    return [token[:-1], "ɹ"]

  return [token]

def cleanup_visemes(visemes, audio_end):
  if not visemes:
    return []

  cleaned = [visemes[0]]

  for curr in visemes[1:]:
    prev = cleaned[-1]

    # Gap → extend previous
    if curr["start"] > prev["end"]:
      prev["end"] = curr["start"]

    # Overlap → trim previous
    elif curr["start"] < prev["end"]:
      prev["end"] = curr["start"]

    cleaned.append(curr)

  # Prepend silence if needed
  if cleaned[0]["start"] > 0.0:
    cleaned.insert(0, {
      "token": "sil",
      "viseme": ipa_to_viseme["sil"],  # or explicit sil
      "start": 0.0,
      "end": cleaned[0]["start"]
    })

  # Extend final viseme
  cleaned[-1]["end"] = audio_end

  return cleaned

def phonemes_to_visemes(phoneme_timings, ipa_to_viseme, audio_end):
  results = []

  for p in phoneme_timings:
    raw_token = p["char"]
    start = p["start"]
    end = p["end"]

    tokens = normalize_token(raw_token)

    for token in tokens:
      # --- Silence handling ---
      if token == " ":
        if start is None or end is None:
          continue

        duration = end - start

        # Short pause → blend into previous viseme
        if results and duration < 0.4:
          results[-1]["end"] = end
          continue

        viseme = ipa_to_viseme.get("sil")

      # --- Length marker ---
      elif token == "ː":
        if results:
          results[-1]["end"] = end
        continue

      # --- Normal phoneme ---
      else:
        viseme = ipa_to_viseme.get(token)

        if viseme is None:
          # Debug but don't crash pipeline
          print(f"No viseme for: {token}")
          continue

      results.append({
        "token": token,
        "viseme": viseme,
        "start": start,
        "end": end
      })

  return cleanup_visemes(results, audio_end)

from pydub import AudioSegment

def get_duration_pydub(file_path):
  audio = AudioSegment.from_file(audio_file)
  # Duration is returned in milliseconds, convert to seconds
  duration_seconds = len(audio) / 1000.0
  return duration_seconds

# Example usage
audio_duration = get_duration_pydub(audio_file)

print(audio_duration)

visemes = phonemes_to_visemes(phoneme_timings, ipa_to_viseme, audio_duration)

# # new
# import os
# import shutil
# viseme_folder_path = '/content/drive/MyDrive/Colab_Notebooks/visemes_microsoft'

# def export_frames(results, audio_duration, output_folder, fps=24):
#   os.makedirs(output_folder, exist_ok=True)

#   total_frames = round(audio_duration * fps)
#   frame_visemes = [0] * total_frames

#   # Token, viseme, start, end
#   for entry in visemes:
#     start_f = int(entry["start"] * fps)
#     end_f = int(entry["end"] * fps)

#     # clamp to bounds
#     start_f = max(0, start_f)
#     end_f   = min(total_frames, end_f)


#     # start_f = max(0, round(entry["start"] * fps))
#     # end_f = min(total_frames, round(entry["end"] * fps))

#     # Ensure at least 1f
#     # if end_f <= start_f:
#     #   end_f = start_f + 1
#     #   if end_f > total_frames:
#     #     end_f = total_frames
#     #     start_f = end_f - 1

#     for f in range(start_f, end_f):
#       frame_visemes[f] = entry["viseme"]

#   for frame_idx, viseme_id in enumerate(frame_visemes):
#     src = os.path.join(viseme_folder_path, f"viseme-id-{viseme_id}.jpg")
#     dst = os.path.join(output_folder, f"frame_{frame_idx:05d}.jpg")
#     shutil.copy(src, dst)
#     secs = round(frame_idx/fps, 2)
#     print(secs, frame_idx, viseme_id)

# export_frames(visemes, audio_duration, "/content/drive/MyDrive/Colab_Notebooks/generated_frames_alone", fps=24)

# os.chdir(r"/content/drive/MyDrive/Colab_Notebooks/generated_frames_alone")
# print(os.getcwd())

# print(audio_name)

# !ffmpeg -framerate 24 -i frame_%05d.jpg -i '/content/drive/MyDrive/Colab_Notebooks/test_audios/i-live-alone.wav' \
# -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" \
# -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest "/content/drive/MyDrive/Colab_Notebooks/whisperx_alone.mp4"